### ISSUE TITLE
Microsoft Defender flags JunkCtrl as malicious

### ISSUE THREAD

**Issue by RoonMoonlight** [builtbybel/JunkCtrl#16]
Hello,

It seems Microsoft is going for revenge to your project and now they marked your software as malicious.
It detects your latest release as following:
* Detected: Trojan:Script/Wacatac.B!ml
* Description: This program is dangerous and executes commands from an attacker.

Is it safe to ignore this error?

**Comment by Belim** [comment]
It is safe. However, VT https://www.virustotal.com/gui/file/0f8f3d2775a023b039f987192e83e74162a6890b377166d3437f09b9db772be2 and Defender are also not reporting anything.

**Comment by RoonMoonlight** [comment]
Weird... I downloaded this [here](https://github.com/builtbybel/JunkCtrl/releases/tag/0.55.0) and it display as malicious
